### ISSUE TITLE
[Suggestions] CBT features/improvements.

### ISSUE THREAD

**Issue by Clueless-AI** [cultbaus/CBT#1]
Hello Cultbaus,
First of all thank you so much for making such a plugin this will make doing big damage feel satisfying just like in wow.
After installing the plugin to do some testing, I noticed that the vanilla flying texts disapeared or got disabled and I was wondering if it's possible to make a toggle for which flying text you want to disable, for example if I wanna use CBT for outgoing damage but keep the vanilla one of incoming damage/status effects.

Being a huge fan of nameplateSCT in WoW, I was thinking if its possible to add skill icons to the damage text to have a good idea of the sources of your damage or big hits which is satisfying and maybe an option to disable the autoattack texts and add a scale modifier to critical strikes and CritDirecthits.

Again thank you so much for taking the time to make this and good luck :D

**Comment by cultbaus** [comment]
Hey, this is still very much early in development, and some of this is in flight, mostly pending configuration overhauls. As of writing this I have implementations (but not releases) for most of these features and I'm working on upstreaming a release with more functionality soon.

Regarding vanilla FlyText events, they're currently being swallowed entirely by CBT, but it's certainly possible to un-handle the events which don't match our filters.

Thanks for the feedback, hope to have something more in line with what you'd expect out of this plugin in the coming days.

**Comment by cultbaus** [comment]
Closing this as I believe all of this functionality is present.
